test:
  clients:
    default:
      database: password_reuse_policy_test
      hosts:
        - localhost:27017
  options:
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_utc: true
